name: thegoatjp
description: The Goat JP test app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  manifest:
    path: ../manifest
  # Core Essentials
  get_it: ^7.2.0
  injectable: ^1.5.3
  dio: ^4.0.6
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  fluro: ^2.0.3
  device_info_plus: ^4.0.0
  package_info_plus: ^1.4.2
  rxdart: ^0.27.3
  rxdart_ext: ^0.2.2
  connectivity_plus: ^2.3.0
  freezed_annotation: ^2.1.0
  async: ^2.8.2
  # Development Helper
  flutter_native_splash:
  alice: ^0.2.5
  device_preview: ^1.1.0
  responsive_sizer: ^3.0.8
  adaptive_theme: ^3.0.0
  # libraries
  lottie: ^1.3.0
  loadmore: ^2.0.1
  cached_network_image: ^3.2.1
  fluttericon: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  injectable_generator: ^1.5.3
  retrofit_generator: ^4.0.1
  freezed: ^2.1.0
  mockito: ^5.3.2

flutter:
  uses-material-design: true

flutter_native_splash:
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  color: "#FFFFFF"
  image: ../resources/image/img_splash_logo.png
  image_dark: ../resources/image/img_splash_logo.png