name: thegoatjp
description: The Goat JP test app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  manifest:
    path: ../manifest
  # Core Essentials
  get_it: ^7.2.0
  injectable: ^1.5.3
  dio: ^4.0.6
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  fluro: ^2.0.3
  device_info_plus: ^4.0.0
  package_info_plus: ^1.4.2
  rxdart: ^0.27.3
  rxdart_ext: ^0.2.2
  connectivity_plus: ^2.3.0
  freezed_annotation: ^2.1.0
  async: ^2.8.2
  kotlin_scope_function: ^1.0.2
  # Development Helper
  flutter_native_splash:
  alice: ^0.2.5
  device_preview: ^1.1.0
  responsive_sizer: ^3.0.8
  adaptive_theme: ^3.0.0
  lottie: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  injectable_generator: ^1.5.3
  retrofit_generator: ^4.0.1
  freezed: ^2.1.0
  mockito: ^5.3.2

flutter:
  uses-material-design: true

flutter_native_splash:
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#FFFFFF"
  # background_image: ../resources/image/img_splash_bg.png

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  #  image:
  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. Currently, it is only supported for Android < v12 and iOS.
  #branding: assets/dart.png

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #branding_mode: bottom

  # The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  # color_dark: "#D92C2F"
  image_dark: ../resources/image/img_splash_logo.png
  #branding_dark: assets/dart_dark.png
  android_12:
  # The image parameter sets the splash screen icon image.  If this parameter is not specified,
  # the app's launcher icon will be used instead.
  # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
  # 640 pixels in diameter.
  # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
  # 768 pixels in diameter.
  #image: assets/android12splash.png

  # Splash screen background color.
  #color: "#42a5f5"

  # App icon background color.
  #icon_background_color: "#eeeeee"

  # The image_dark parameter and icon_background_color_dark set the image and icon background
  # color when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above.
  #image_dark: assets/android12splash-invert.png
  #color_dark: "#042a49"
  #icon_background_color_dark: "#111111"